snowsql_config_path = "~/.snowsql/config"
snowsql_connection_name = "dev"

[default]
input_parameters = "(userAgent varchar)"
return_type = "varchar"
file = "app.zip"
name = "device_detector_udf"
handler = "app.main"
execute_as_caller = true

[dev]
database = "HOL_DB"
schema = "ANALYTICS"
warehouse = "HOL_WH"
role = "HOL_ROLE"
overwrite = true
